apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: skip-gate-matrix
on:
  workflow_dispatch:
jobs:
  always-skip:
    if: ${{ false }}
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "always-skip should be skipped"

  run-anchor:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "run-anchor should run"

  regular-needs-skip:
    needs: [always-skip]
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "regular-needs-skip should be skipped"

  regular-needs-ok:
    needs: [run-anchor]
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "regular-needs-ok should run"

  custom-needs-skip:
    needs: [always-skip]
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 12ea0094-8d45-4942-bdbf-fe9d0a58157a
      disallowLaunchByUser: false
      instructions: should be skipped before approval

  edge-needs-skip:
    needs: [always-skip]
    runs-on: [self-hosted, os:linux]
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "edge-needs-skip should be skipped"

  reusable-needs-skip:
    needs: [always-skip]
    uses: rajnish-cloudbees/cloudbees-workflow-testing/.cloudbees/workflows/callable-skip-73f17edc-df30-46cb-a28a-228d7818eb10.yaml
